services:
  website:
    image: ghcr.io/gc-stats/website:latest
    container_name: gcs-website
    env_file: .env
    restart: always
    networks:
      - gcs_network

networks:
  gcs_network:
    external: true
