<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('change_requests', function (Blueprint $table) {
            $table->id();

            // Polymorphic target (team, player, tournament, ...), via the
            // app-wide Relation::morphMap in AppServiceProvider.
            $table->string('subject_type');
            $table->unsignedBigInteger('subject_id');

            // Nullable: null means the request was generated by the system
            // (e.g. a stats-fetch mismatch), not a human — see UserReport's
            // reporter_id / Sanction's issued_by for the same nullOnDelete
            // anti-erasure pattern.
            $table->foreignId('requested_by')->nullable()->constrained('users')->nullOnDelete();
            $table->text('reason')->nullable();

            $table->string('status')->default('pending');

            $table->foreignId('closed_by')->nullable()->constrained('users')->nullOnDelete();
            $table->timestamp('closed_at')->nullable();

            $table->timestamps();

            $table->index(['subject_type', 'subject_id']);
            $table->index('status');
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('change_requests');
    }
};
