<?php

/**
 * GC-Stats — Tournament preview controller
 *
 * Renders a time-limited preview of a tournament page (including inactive
 * tournaments) using a one-time code generated by the internal API.
 *
 * @copyright Copyright (c) 2026 Alice Alleman — GC-Stats-Website
 * @license   https://github.com/GC-Stats/Website/blob/main/LICENSE GC-Stats License v1.0
 *
 * @link      https://github.com/GC-Stats/Website
 */

namespace App\Http\Controllers;

use App\Models\GamePlayerStat;
use App\Models\Matchs;
use App\Models\News;
use App\Models\Team;
use App\Models\Tournament;
use App\Models\TournamentPhase;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\DB;

class TournamentPreviewController extends Controller
{
    public function show(string $code)
    {
        $tournamentId = Cache::get("tournament_preview_{$code}");

        if (! $tournamentId) {
            abort(404);
        }

        $tournament = Tournament::with(['teams:id,name'])->findOrFail($tournamentId);

        $news = News::with(['author', 'publisher'])
            ->published()
            ->forLocale(app()->getLocale())
            ->whereHas('tournaments', fn ($q) => $q->where('tournaments.id', $tournamentId))
            ->latest('published_at')
            ->take(3)
            ->get()
            ->toArray();

        $phasesRaw = DB::table('tournament_phases')
            ->where('tournament_id', $tournamentId)
            ->orderBy('order', 'asc')
            ->get()
            ->map(fn ($x) => (array) $x)
            ->toArray();

        $phaseIds = array_column($phasesRaw, 'id');

        $matchesRaw = [];
        if (! empty($phaseIds)) {
            $matchesRaw = DB::table('matches')
                ->whereIn('phase_id', $phaseIds)
                ->orderBy('round_number', 'asc')
                ->orderBy('match_order', 'asc')
                ->get()
                ->map(fn ($x) => (array) $x)
                ->toArray();
        }

        $matchIds = array_column($matchesRaw, 'id');

        $gameMapsByMatch = [];
        if (! empty($matchIds)) {
            foreach (DB::table('game_maps')->whereIn('match_id', $matchIds)->orderBy('order', 'asc')->get() as $gm) {
                $gameMapsByMatch[$gm->match_id][] = [
                    'team_a_score' => $gm->team_a_score,
                    'team_b_score' => $gm->team_b_score,
                ];
            }
        }

        $teamIds = array_unique(array_filter(array_merge(
            array_column($matchesRaw, 'team_a_id'),
            array_column($matchesRaw, 'team_b_id')
        )));

        $teamsRaw = [];
        if (! empty($teamIds)) {
            $teamsRaw = Team::with('currentLogo')
                ->whereIn('id', $teamIds)
                ->get(['id', 'name'])
                ->keyBy('id')
                ->map(fn ($x) => $x->toArray())
                ->toArray();
        }

        $matchesByPhase = [];
        foreach ($matchesRaw as $m) {
            $pId = $m['phase_id'];

            $teamA = $teamsRaw[$m['team_a_id']] ?? null;
            $teamB = $teamsRaw[$m['team_b_id']] ?? null;

            $matchesByPhase[$pId][] = [
                'id' => $m['id'],
                'round_name' => $m['round_name'] ?? null,
                'phase_id' => $pId,
                'team_a_id' => $m['team_a_id'],
                'team_b_id' => $m['team_b_id'],
                'team_a_score' => $m['team_a_score'],
                'team_b_score' => $m['team_b_score'],
                'round_number' => $m['round_number'],
                'match_order' => $m['match_order'],
                'status' => $m['status'] ?? null,
                'scheduled_at' => $m['scheduled_at'],
                'team_a' => $teamA,
                'team_b' => $teamB,
                'game_maps' => $gameMapsByMatch[$m['id']] ?? [],
            ];
        }

        $allPhases = [];
        foreach ($phasesRaw as $phase) {
            $phase['matches'] = $matchesByPhase[$phase['id']] ?? [];
            $allPhases[] = $phase;
        }

        $groupedPhases = [];
        foreach ($allPhases as $phase) {
            $groupedPhases[$phase['parent_id']][] = $phase;
        }

        $formatPhase = function ($phase) use (&$formatPhase, $groupedPhases) {
            $data = [
                'id' => $phase['id'],
                'name' => $phase['name'],
                'format' => $phase['format'],
            ];

            $children = $groupedPhases[$phase['id']] ?? [];

            if (! empty($children)) {
                $data['children'] = array_map(fn ($c) => $formatPhase($c), $children);
            } else {
                $data['matches'] = array_map(function ($m) {
                    return [
                        'id' => $m['id'],
                        'round_name' => $m['round_name'],
                        'phase_id' => $m['phase_id'],
                        'team_a_id' => $m['team_a_id'],
                        'team_b_id' => $m['team_b_id'],
                        'team_a_name' => $m['team_a']['name'] ?? null,
                        'team_b_name' => $m['team_b']['name'] ?? null,
                        'team_a_logo' => $m['team_a']['logo'] ?? null,
                        'team_b_logo' => $m['team_b']['logo'] ?? null,
                        'team_a_score' => $m['team_a_score'],
                        'team_b_score' => $m['team_b_score'],
                        'round_number' => $m['round_number'],
                        'match_order' => $m['match_order'],
                        'status' => $m['status'],
                        'scheduled_at' => $m['scheduled_at'] ? Carbon::parse($m['scheduled_at'])->toDateTimeString() : null,
                        'game_maps' => $m['game_maps'] ?? [],
                    ];
                }, $phase['matches'] ?? []);
            }

            return $data;
        };

        $rootPhases = [];
        foreach ($allPhases as $phase) {
            if ($phase['parent_id'] === null) {
                $rootPhases[] = $formatPhase($phase);
            }
        }

        $phaseIds = array_column($allPhases, 'id');
        $recentMatches = Matchs::whereIn('phase_id', $phaseIds)
            ->with(['teamA:id,name', 'teamB:id,name', 'tournamentPhase:id,name'])
            ->latest('scheduled_at')
            ->take(9)
            ->get()
            ->map(fn ($m) => [
                'id' => $m->id,
                'status' => $m->status,
                'scheduled_at' => $m->scheduled_at?->toDateTimeString(),
                'team_a_name' => $m->teamA->name ?? null,
                'team_b_name' => $m->teamB->name ?? null,
                'team_a_score' => $m->team_a_score,
                'team_b_score' => $m->team_b_score,
                'team_a' => $m->teamA ? [
                    'id' => $m->teamA->id,
                    'name' => $m->teamA->name,
                    'logo' => $m->teamA->logo,
                ] : null,
                'team_b' => $m->teamB ? [
                    'id' => $m->teamB->id,
                    'name' => $m->teamB->name,
                    'logo' => $m->teamB->logo,
                ] : null,
                'tournament_phase' => ['name' => $m->tournamentPhase->name ?? ''],
            ]);

        return response()
            ->view('tournament.show', [
                'tournament' => [
                    'id' => $tournament->id,
                    'name' => $tournament->name,
                    'status' => $tournament->status,
                    'start_date' => $tournament->start_date?->toDateTimeString(),
                    'end_date' => $tournament->end_date?->toDateTimeString(),
                    'region' => $tournament->region,
                    'prize_pool' => $tournament->prize_pool,
                    'description' => $tournament->description,
                    'location' => $tournament->location,
                    'logo' => $tournament->logo,
                ],
                'teams' => (function () use ($tournament) {
                    $teamIds = $tournament->teams->pluck('id');

                    $rostersByTeam = GamePlayerStat::query()
                        ->join('players', 'game_player_stats.player_id', '=', 'players.id')
                        ->where('game_player_stats.tournament_id', $tournament->id)
                        ->whereIn('game_player_stats.team_id', $teamIds)
                        ->select('players.id', 'players.handle', 'game_player_stats.team_id')
                        ->distinct()
                        ->orderBy('players.handle')
                        ->get()
                        ->groupBy('team_id');

                    return $tournament->teams->map(function ($team) use ($rostersByTeam) {
                        $roster = $rostersByTeam->get($team->id, collect());

                        return [
                            'id' => $team->id,
                            'name' => $team->name,
                            'logo' => $team->logo,
                            'roster' => $roster->map(fn ($p) => [
                                'id' => $p->id,
                                'handle' => $p->handle,
                            ])->toArray(),
                        ];
                    })->toArray();
                })(),
                'matches' => $recentMatches->toArray(),
                'root_phases' => $rootPhases,
                'previewCode' => $code,
                'news' => $news,
            ])
            ->header('Vary', 'Accept-Language');
    }

    public function matches(string $code, Request $request)
    {
        $tournamentId = Cache::get("tournament_preview_{$code}");

        if (! $tournamentId) {
            abort(404);
        }

        $phaseId = $request->get('phase_id');
        $teamId = $request->get('team_id');
        $roundName = $request->get('round');

        $tournament = Tournament::findOrFail($tournamentId);

        $phases = TournamentPhase::where('tournament_id', $tournamentId)
            ->orderBy('order')
            ->get(['id', 'parent_id', 'name', 'format'])
            ->keyBy('id');

        $phaseOptions = $phases->map(function ($phase) use ($phases) {
            $name = $phase->name;
            $parent = $phase->parent_id ? $phases->get($phase->parent_id) : null;
            if ($parent) {
                $name = $parent->name.' - '.$name;
            }

            return [
                'id' => $phase->id,
                'name' => $name,
                'format' => $phase->format,
            ];
        })->values()->all();

        $teams = $tournament->teams()
            ->get(['teams.id', 'teams.name'])
            ->map(fn ($team) => ['id' => $team->id, 'name' => $team->name])
            ->sortBy('name')
            ->values()
            ->all();

        $rounds = Matchs::where('tournament_id', $tournamentId)
            ->whereIn('phase_id', $phases->whereIn('format', ['swiss', 'round_robin'])->pluck('id'))
            ->whereNotNull('round_name')
            ->select('phase_id', 'round_name')
            ->distinct()
            ->get()
            ->groupBy('phase_id')
            ->map(fn ($group) => $group->pluck('round_name')->unique()->values()->all())
            ->all();

        $phaseIds = null;
        if ($phaseId) {
            $phaseIds = collect([(int) $phaseId]);
            $queue = [(int) $phaseId];
            while (! empty($queue)) {
                $current = array_shift($queue);
                $children = $phases->where('parent_id', $current)->pluck('id');
                $phaseIds = $phaseIds->merge($children);
                $queue = array_merge($queue, $children->all());
            }
        }

        $paginated = Matchs::query()
            ->select([
                'id',
                'round_name',
                'scheduled_at',
                'team_a_score',
                'team_b_score',
                'status',
                'team_a_id',
                'team_b_id',
                'tournament_id',
                'phase_id',
                'match_order',
            ])
            ->where('tournament_id', $tournamentId)
            ->when($phaseIds, fn ($query) => $query->whereIn('phase_id', $phaseIds))
            ->when($teamId, fn ($query) => $query->where(function ($query) use ($teamId) {
                $query->where('team_a_id', $teamId)->orWhere('team_b_id', $teamId);
            }))
            ->when($roundName, fn ($query) => $query->where('round_name', $roundName))
            ->with([
                'teamA:id,name',
                'teamB:id,name',
                'tournamentPhase:id,name',
            ])
            ->orderBy('scheduled_at', 'desc')
            ->orderBy('match_order', 'asc')
            ->paginate(10)
            ->withQueryString();

        $matches = $paginated->through(fn ($match) => [
            'id' => $match->id,
            'round_name' => $match->round_name,
            'scheduled_at' => $match->scheduled_at?->toDateTimeString(),
            'team_a_score' => (int) $match->team_a_score,
            'team_b_score' => (int) $match->team_b_score,
            'status' => $match->status,
            'team_a' => $match->teamA ? [
                'id' => $match->teamA->id,
                'name' => $match->teamA->name,
                'logo' => $match->teamA->logo,
            ] : null,
            'team_b' => $match->teamB ? [
                'id' => $match->teamB->id,
                'name' => $match->teamB->name,
                'logo' => $match->teamB->logo,
            ] : null,
            'phase_name' => $match->tournamentPhase->name ?? '',
        ]);

        return response()
            ->view('tournament.matches', [
                'tournament' => [
                    'id' => $tournament->id,
                    'name' => $tournament->name,
                    'status' => $tournament->status,
                    'start_date' => $tournament->start_date?->toDateTimeString(),
                    'end_date' => $tournament->end_date?->toDateTimeString(),
                    'region' => $tournament->region,
                    'prize_pool' => $tournament->prize_pool,
                    'description' => $tournament->description,
                    'location' => $tournament->location,
                    'logo' => $tournament->logo,
                ],
                'matches' => $matches,
                'filters' => [
                    'phases' => $phaseOptions,
                    'teams' => $teams,
                    'rounds' => $rounds,
                ],
                'phaseId' => $phaseId,
                'teamId' => $teamId,
                'roundName' => $roundName,
                'previewCode' => $code,
            ])
            ->header('Vary', 'Accept-Language');
    }
}
