<?php

/**
 * GC-Stats — Admin: change requests
 *
 * Review queue for proposed edits to any polymorphic subject (team, player,
 * tournament, ...), submitted either by a user or generated by the system
 * (e.g. a roster mismatch detected while fetching match stats — see
 * RosterMismatchDetector). Gated behind `change-requests.*` at the route
 * level (routes/admin.php).
 *
 * @copyright Copyright (c) 2026 Alice Alleman — GC-Stats-Website
 * @license   https://github.com/GC-Stats/Website/blob/main/LICENSE GC-Stats License v1.0
 *
 * @link      https://github.com/GC-Stats/Website
 */

namespace App\Http\Controllers\Admin;

use App\Exceptions\ChangeRequestItemAlreadyResolvedException;
use App\Exceptions\SanctionRequiresSuperAdminException;
use App\Http\Controllers\Public\Controller;
use App\Models\ChangeRequest;
use App\Models\ChangeRequestItem;
use App\Models\Player;
use App\Models\Sanction;
use App\Models\Team;
use App\Services\ChangeRequests\ChangeRequestApplierRegistry;
use App\Services\ChangeRequestService;
use App\Services\RosterService;
use App\Services\SanctionService;
use Illuminate\Contracts\View\View;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Relations\Relation;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Validation\Rule;

class ChangeRequestController extends Controller
{
    private const STATUSES = [
        ChangeRequest::STATUS_PENDING,
        ChangeRequest::STATUS_AWAITING_REQUESTER_REPLY,
        ChangeRequest::STATUS_PARTIALLY_ACCEPTED,
        ChangeRequest::STATUS_ACCEPTED,
        ChangeRequest::STATUS_REJECTED,
        ChangeRequest::STATUS_WITHDRAWN,
    ];

    private const SUBJECT_TYPES = ['team', 'player', 'tournament'];

    private const SORTABLE = ['requested_by', 'submitted_at'];

    private const SANCTION_DURATIONS = ['30', '60', '90', '180', 'permanent'];

    public function index(Request $request): View
    {
        $status = $request->get('status', ChangeRequest::STATUS_PENDING);

        [$sort, $direction] = $this->resolveSort($request, self::SORTABLE, 'submitted_at', 'desc');

        $requestedByName = $request->string('requested_by_name')->toString() ?: null;
        $subjectType = $request->string('subject_type')->toString() ?: null;
        $subjectType = in_array($subjectType, self::SUBJECT_TYPES, true) ? $subjectType : null;
        $subjectQuery = $request->string('subject_query')->toString() ?: null;
        $field = $request->string('field')->toString() ?: null;
        $dateFrom = $request->string('date_from')->toString() ?: null;
        $dateTo = $request->string('date_to')->toString() ?: null;

        $fieldOptions = ChangeRequestItem::query()
            ->whereNotNull('field')
            ->distinct()
            ->orderBy('field')
            ->pluck('field');

        $requests = ChangeRequest::with(['subject', 'requestedBy:id,name,username', 'items'])
            ->when(in_array($status, self::STATUSES, true), fn ($query) => $query->where('status', $status))
            ->when($subjectType, fn ($query) => $query->where('subject_type', $subjectType))
            ->when($requestedByName, fn ($query) => $query->whereHas(
                'requestedBy',
                fn ($q) => $q->where('name', 'like', "%{$requestedByName}%")->orWhere('username', 'like', "%{$requestedByName}%")
            ))
            ->when($field, fn ($query) => $query->whereHas('items', fn ($q) => $q->where('field', $field)))
            ->when($subjectQuery, function (Builder $query) use ($subjectQuery, $subjectType) {
                $types = $subjectType ? [$subjectType] : self::SUBJECT_TYPES;
                $classes = array_map(fn ($type) => Relation::getMorphedModel($type), $types);

                $query->whereHasMorph('subject', $classes, function (Builder $q, string $type) use ($subjectQuery) {
                    $q->where($type === Player::class ? 'handle' : 'name', 'like', "%{$subjectQuery}%");
                });
            })
            ->when($dateFrom, fn ($query) => $query->whereDate('created_at', '>=', $dateFrom))
            ->when($dateTo, fn ($query) => $query->whereDate('created_at', '<=', $dateTo))
            ->when($sort === 'requested_by', fn ($query) => $query
                ->select('change_requests.*')
                ->leftJoin('users as requesters', 'requesters.id', '=', 'change_requests.requested_by')
                ->orderBy('requesters.name', $direction))
            ->when($sort === 'submitted_at', fn ($query) => $query->orderBy('created_at', $direction))
            ->orderByDesc('change_requests.id')
            ->paginate(25)
            ->withQueryString();

        return view('admin.change-requests.index', [
            'requests' => $requests,
            'status' => $status,
            'statuses' => self::STATUSES,
            'sort' => $sort,
            'direction' => $direction,
            'subjectTypes' => self::SUBJECT_TYPES,
            'requestedByName' => $requestedByName,
            'subjectType' => $subjectType,
            'subjectQuery' => $subjectQuery,
            'field' => $field,
            'fieldOptions' => $fieldOptions,
            'dateFrom' => $dateFrom,
            'dateTo' => $dateTo,
        ]);
    }

    public function show(ChangeRequest $changeRequest): View
    {
        $changeRequest->load(['subject', 'requestedBy:id,name,username', 'closedBy:id,name,username', 'items.resolvedBy:id,name,username', 'messages.user:id,name,username']);

        return view('admin.change-requests.show', [
            'request' => $changeRequest,
        ]);
    }

    public function acceptItem(Request $request, ChangeRequestItem $changeRequestItem, ChangeRequestService $changeRequests): RedirectResponse
    {
        abort_if($changeRequestItem->status !== ChangeRequestItem::STATUS_PENDING, 409, 'This item has already been resolved.');

        $validated = $request->validate([
            'resolution_note' => ['nullable', 'string', 'max:2000'],
        ]);

        try {
            $changeRequests->acceptItem($changeRequestItem, $request->user(), $validated['resolution_note'] ?? null);
        } catch (ChangeRequestItemAlreadyResolvedException $e) {
            abort(409, $e->getMessage());
        }

        return redirect()->route('admin.change-requests.show', $changeRequestItem->change_request_id)
            ->with('status', 'change-request-item-accepted');
    }

    public function rejectItem(Request $request, ChangeRequestItem $changeRequestItem, ChangeRequestService $changeRequests): RedirectResponse
    {
        abort_if($changeRequestItem->status !== ChangeRequestItem::STATUS_PENDING, 409, 'This item has already been resolved.');

        $validated = $request->validate([
            'resolution_note' => ['nullable', 'string', 'max:2000'],
        ]);

        try {
            $changeRequests->rejectItem($changeRequestItem, $request->user(), $validated['resolution_note'] ?? null);
        } catch (ChangeRequestItemAlreadyResolvedException $e) {
            abort(409, $e->getMessage());
        }

        return redirect()->route('admin.change-requests.show', $changeRequestItem->change_request_id)
            ->with('status', 'change-request-item-rejected');
    }

    public function withdraw(Request $request, ChangeRequest $changeRequest, ChangeRequestService $changeRequests): RedirectResponse
    {
        $changeRequests->withdraw($changeRequest, $request->user());

        return redirect()->route('admin.change-requests.show', $changeRequest)->with('status', 'change-request-withdrawn');
    }

    /**
     * Suspend the requester with a fixed-length or permanent ban, issued
     * straight out of the change request queue by whoever is handling it
     * (same `change-requests.reject` gate as withdraw/reject — no separate
     * `sanctions.*` permission required). Only applies to user-submitted
     * requests; system-generated ones have no requester to sanction.
     */
    public function sanction(Request $request, ChangeRequest $changeRequest, SanctionService $sanctions): RedirectResponse
    {
        abort_if($changeRequest->requested_by === null, 403, 'This request has no requester to sanction.');

        $validated = $request->validate([
            'duration' => ['required', 'string', Rule::in(self::SANCTION_DURATIONS)],
            'reason' => ['required', 'string', 'max:2000'],
        ]);

        try {
            // Locks the row before the already-sanctioned check so two
            // concurrent submits (double-click) can't both pass the check
            // before either writes sanctioned_at.
            DB::transaction(function () use ($changeRequest, $validated, $request, $sanctions) {
                $locked = ChangeRequest::whereKey($changeRequest->id)->lockForUpdate()->first();

                abort_if($locked->sanctioned_at !== null, 409, 'A sanction has already been issued from this request.');

                $sanctions->issue($changeRequest->requestedBy, $request->user(), [
                    'type' => Sanction::TYPE_SUSPENSION,
                    'reason' => sprintf('[Change request #%d] %s', $changeRequest->id, $validated['reason']),
                    'ends_at' => $validated['duration'] === 'permanent' ? null : now()->addDays((int) $validated['duration']),
                ]);

                $locked->update(['sanctioned_at' => now()]);
            });
        } catch (SanctionRequiresSuperAdminException $e) {
            return back()->withErrors(['reason' => $e->getMessage()]);
        }

        return redirect()->route('admin.change-requests.show', $changeRequest)->with('status', 'change-request-sanction-issued');
    }

    public function storeMessage(Request $request, ChangeRequest $changeRequest, ChangeRequestService $changeRequests): RedirectResponse
    {
        abort_if($changeRequest->isResolved(), 403, 'This request has been resolved — the discussion is closed.');

        $validated = $request->validate([
            'body' => ['required', 'string', 'max:2000'],
        ]);

        $changeRequests->addMessage($changeRequest, $request->user(), $validated['body'], needsRequesterReply: $request->boolean('needs_requester_reply'));

        return redirect()->route('admin.change-requests.show', $changeRequest)->with('status', 'change-request-message-added');
    }

    public function create(ChangeRequestApplierRegistry $appliers): View
    {
        $fieldsByType = collect(self::SUBJECT_TYPES)->mapWithKeys(fn ($type) => [
            $type => $appliers->fieldsFor(Relation::getMorphedModel($type)),
        ]);

        return view('admin.change-requests.create', [
            'subjectTypes' => self::SUBJECT_TYPES,
            'fieldsByType' => $fieldsByType,
            'roles' => RosterService::ROLES,
        ]);
    }

    /**
     * Every row is either a plain field (`new_value` as free text, `old_value`
     * snapshotted server-side from the subject's current attribute — never
     * trusted from the client) or, for Player's `roster` field, a team/role/
     * joined_at triple applied through RosterService like any other roster
     * edit.
     */
    public function store(Request $request, ChangeRequestApplierRegistry $appliers, ChangeRequestService $changeRequests): RedirectResponse
    {
        $validated = $request->validate([
            'subject_type' => ['required', 'string', Rule::in(self::SUBJECT_TYPES)],
            'subject_id_team' => ['nullable', 'integer', 'exists:teams,id'],
            'subject_id_player' => ['nullable', 'integer', 'exists:players,id'],
            'subject_id_tournament' => ['nullable', 'integer', 'exists:tournaments,id'],
            'reason' => ['nullable', 'string', 'max:2000'],
            'items' => ['required', 'array', 'min:1'],
            'items.*.field' => ['nullable', 'string'],
            'items.*.new_value' => ['nullable', 'string', 'max:2000'],
            'items.*.team_id' => ['nullable', 'integer', 'exists:teams,id'],
            'items.*.role' => ['nullable', 'string', Rule::in(RosterService::ROLES)],
            'items.*.joined_at' => ['nullable', 'date'],
        ]);

        $subjectClass = Relation::getMorphedModel($validated['subject_type']);
        $subjectId = $validated['subject_id_'.$validated['subject_type']] ?? null;
        abort_unless($subjectId, 422, 'A subject must be selected.');

        $subject = $subjectClass::findOrFail($subjectId);

        $allowedFields = $appliers->fieldsFor($subjectClass);
        $rows = array_filter($validated['items'], fn ($row) => ! empty($row['field']));
        abort_if(empty($rows), 422, 'At least one field must be proposed.');

        $items = [];

        foreach ($rows as $row) {
            abort_unless(in_array($row['field'], $allowedFields, true), 422, "Unknown field: {$row['field']}");

            if ($row['field'] === 'roster') {
                abort_unless($subject instanceof Player, 422, 'roster only applies to players.');
                abort_unless(! empty($row['team_id']) && ! empty($row['joined_at']), 422, 'roster changes require a team and a join date.');

                $team = Team::findOrFail($row['team_id']);
                $currentTeam = $subject->teams()->wherePivot('left_at', null)->first();

                $items[] = [
                    'field' => 'roster',
                    'old_value' => $currentTeam ? ['team_id' => $currentTeam->id, 'team_name' => $currentTeam->name] : null,
                    'new_value' => ['team_id' => $team->id, 'team_name' => $team->name, 'role' => $row['role'] ?? 'player', 'joined_at' => $row['joined_at']],
                ];

                continue;
            }

            $items[] = [
                'field' => $row['field'],
                'old_value' => $subject->{$row['field']},
                'new_value' => $row['new_value'] ?? null,
            ];
        }

        $changeRequest = $changeRequests->create($subject, $request->user(), $validated['reason'] ?? null, $items);

        return redirect()->route('admin.change-requests.show', $changeRequest)->with('status', 'change-request-created');
    }
}
