name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  release:
    types: [published]
  workflow_dispatch:

jobs:
  run-checks:
    uses: ./.github/workflows/checks.yml

  deploy-preprod:
    needs: [run-checks]
    if: success() && github.event_name == 'push'
    uses: ./.github/workflows/deploy.yml
    with:
      environment: preprod
      version: ${{ github.event.release.tag_name }}
    secrets: inherit

  deploy-prod:
    needs: [run-checks]
    if: success() && github.event_name == 'release'
    uses: ./.github/workflows/deploy.yml
    with:
      environment: prod
      version: ${{ github.event.release.tag_name }}
    secrets: inherit
